language: node_js

node_js:
- 4
- 5
- node

os:
- linux

sudo: false

branches:
  only: master

script:
- npm test

deploy:
- provider: s3
  bucket: nexis-et-web
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: ap-southeast-2
  local_dir: app
  skip_cleanup: true
  acl: public_read

env:
  global:
  - secure: BFbtkLZ/pJhJb8BNre34c36hLp65dxZ/2pcG9gYaZ5H2susFbbnL1cdXcJ5TUVfx2FH9IAwp5kPercrl6h6eEOQQ3hBa54gkEr/IL8Qxqf1YyxfpcXHi1XmbKbefOG/jPnB2G1V3NfPr7zjsnS6kSbme28Hnl6fnmq35VXTn+iQM2g3tkiQ63K0O/NcvFJvMO/5yqajP/QZmD+jTVeeDjsk0+UYV5fgydcCmLq86hu2rUp9juQVVLxHjet6ZRhOuohfI1x7PUsbENLAXor/QWjkEf/iE7dEE3wyqAKSaoACkPb2EI1lvZ81JLLfPDLrQGfYTUIzPew3sSOAh+oZ1pk/1IWPVfnp3JPgp8aB/FhXZ9d0Z0al1/RdpXuhYIgefPlPWNHEpwgIs2c+aS3Sad8FAUrLFLsb84q7cw3pwy1OdILkqrQil5u3FO4mzRrPWJXW7uqrZQW9jNvxoHygL9JwEUCkS/9cF4A4C/q9FF9VEGGmITWqBQDNJ9YvlnekEE5e9hcRMl7kv4HbFqFGkhXbzkFQvan3j26S4hw60WS7K8mwrPwRA3PVYxqa/TjotcBk1NRgQc5liqWPE9/uMeEsvCqpUNg1GLXhMZqcA4i4yOWLUcuZUmanMVXsHwn9VePcnC3ZRRAMAmQNOrehD6gEmxTSHBM2CQw8BWAk/Rx4=
  - secure: zLOrZNQrQIdP+3GmNta2PeUCRPAB2KRRdzFGqYrJlFfVyFOtKdRAun2EnixvV7PTiLW7Pq8NnYnTjM40BHqRx9TKkDpJ1gjGQQlMVDOeGISXuUkeRLGO8kqW05O/WGrPdO5K6/j2P5kCNyerQJOvyNRO5v/vPpVPXvRkQxC3c/+tYxjkswOHCpFQLQSBhq9TP9F5BiL/eg5trIZ0SYMpVfksJ4buDXviN7o15RTH2K+y0YXsc45c9jkA0Gdx6YVNZEpSmTMYGv15KSh/vEm7q4hyR1pSWl7Z3Vt/dg/4psnevt+APGfN9SBzfzs0x0dW/ExCoE+DCHTK9Mndtt1vcQ8T9dtW+vKghqHdkGegaByMTlUVVZN7RgexJ11NYgV+UtvR6uuy3ei32FtcrqLcfGfZhdkSeyBnxoenAqpq0Q6fUI6P2fHytwXjQN09OgA49+ueAFuR4tPAA1hvlgBGnJhUEWBn85Hdw/nnQdfcRHC+/yjMmS74aTaoa4u+3gIiLCSQz0tmQuAZYx8RplGkMCXc8ZIngxkBUjFt7+F4jbPoKbEaGj7tz2YJRz/jFYAYu4rJHcPnBr+qM3CwfO1SQo/60VHYLZROf3CTb/7u3uPnEMr8zTPJm3y6W5b+3eW+gftS7VJhQQZzZFE2WfTsvgKnp5r93YeNq2zH3r5zlOQ=
