language: node_js

node_js:
  - 4
  - 5
  - node

sudo: false

branches:
  only: master

deploy:
  provider: s3
  bucket: test-nexis-deploy
  region: ap-southeast-2
  local_dir: app
  skip_cleanup: true
  
